export type User = { id: string; name?: string; email: string; biometricsEnabled?: boolean };
export type LoginRequest = { email: string; password: string };
export type RegisterRequest = { email: string; password: string };
export type LoginResponse = { accessToken: string; refreshToken: string; user: User };
export type RegisterResponse = LoginResponse;
export type BankAccount = {
  id: string;
  connectedAccountId: string;
  externalId: string;
  type: 'BANK' | 'CREDIT' | string;
  balance: number;
  currency: 'BRL';
  lastSyncAt: string | null;
};
export type Account = {
  id: string;
  bankName: string;
  logoUrl?: string | null;
  primaryColor?: string | null;
  type?: string;
  balance?: number;
  currency?: 'BRL';
  lastSyncedAt?: string | null;
  status?: string;
  bankAccounts?: BankAccount[];
};
export type Transaction = {
  id: string;
  accountId?: string;
  accountName?: string | null;
  accountLogoUrl?: string | null;
  occurredAt: string;
  description: string;
  originalDescription?: string;
  alias?: string | null;
  amount: number;
  currency?: 'BRL';
  merchantName?: string | null;
  categoryId?: string | null;
  categoryName?: string | null;
  categoryIcon?: string | null;
  categoryColor?: string | null;
  // null = decisão automática; true = forçar assinatura; false = forçar fora
  isSubscriptionOverride?: boolean | null;
  pending?: boolean;
};
export type Category = { id: string; name: string; icon: string | null; color: string | null };
export type Dashboard = {
  month: string;
  totalBalance: number;
  monthlyIncome: number;
  monthlyExpenses: number;
  topCategories: Array<{ categoryId: string; categoryName: string; categoryIcon: string | null; total: number; percentage: number }>;
  recentTransactions: Transaction[];
};
export type PaginatedTransactions = { items: Transaction[]; nextCursor: string | null };
export type BinanceAsset = { symbol: string; name: string; quantity: number; valueBRL: number; change24h: number };
export type BinanceWallet = { connected: boolean; totalBRL: number; assets: BinanceAsset[] };
export type Quote = { symbol: string; priceBRL: number; updatedAt: string };
export type Order = {
  id: string;
  symbol: string;
  side: 'buy' | 'sell';
  amountBRL: number;
  executedQuantity: number | null;
  executedPriceBRL: number | null;
  status: 'pending' | 'filled' | 'failed';
  createdAt: string;
  errorMessage: string | null;
};
